services:
    postgres:
        container_name: postgres
        image: postgres:18-alpine
        environment:
            POSTGRES_USER: ${DB_USER:?ERROR-DB_USER is not set}
            POSTGRES_PASSWORD: ${DB_PASSWORD:?ERROR-DB_PASSWORD is not set}
            POSTGRES_DB: ${DB_NAME:?ERROR-DB_NAME is not set}
        ports:
            - ${DB_PORT:?ERROR-DB_PORT is not set}:5432
        volumes:
            - ./pg_volume:/var/lib/postgresql
        networks:
            - orchestrix

    # migrate:
    #     container_name: go_migrate
    #     image: migrate/migrate:v4.17.0
    #     volumes:
    #         - ../services/scheduler/db/migrations:/migrations
    #     depends_on:
    #         - postgres
    #     networks:
    #         - orchestrix

    # services
    # scheduler:
    #     build:
    #         context: ..
    #         dockerfile: services/scheduler/Dockerfile
    #     container_name: scheduler
    #     ports:
    #         - ${SCHEDULER_SERVER_PORT:?ERROR-SERVER_PORT is not set}:8000
    #     env_file:
    #         - ../services/scheduler/.env
    #     networks:
    #         - orchestrix

networks:
    orchestrix:
        name: orchestrix
        driver: bridge
