// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db_sqlc

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Task struct {
	ID          pgtype.UUID      `db:"id" json:"id"`
	Task        string           `db:"task" json:"task"`
	ScheduledAt pgtype.Timestamp `db:"scheduled_at" json:"scheduled_at"`
	PickedAt    pgtype.Timestamp `db:"picked_at" json:"picked_at"`
	StartedAt   pgtype.Timestamp `db:"started_at" json:"started_at"`
	CompletedAt pgtype.Timestamp `db:"completed_at" json:"completed_at"`
	FailedAt    pgtype.Timestamp `db:"failed_at" json:"failed_at"`
	Error       pgtype.Text      `db:"error" json:"error"`
	CreatedAt   pgtype.Timestamp `db:"created_at" json:"created_at"`
	UpdatedAt   pgtype.Timestamp `db:"updated_at" json:"updated_at"`
}
