// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db_sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	InsertTask(ctx context.Context, arg InsertTaskParams) (pgtype.UUID, error)
}

var _ Querier = (*Queries)(nil)
