// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: tasks.sql

package db_sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const insertTask = `-- name: InsertTask :one
INSERT INTO tasks(task, scheduled_at)
    VALUES ($1, $2)
RETURNING
    id
`

type InsertTaskParams struct {
	Task        string           `db:"task" json:"task"`
	ScheduledAt pgtype.Timestamp `db:"scheduled_at" json:"scheduled_at"`
}

func (q *Queries) InsertTask(ctx context.Context, arg InsertTaskParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, insertTask, arg.Task, arg.ScheduledAt)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}
